### PR TITLE
Please consider this changes

### PR DESCRIPTION
**Pull request by silvioprog**

### CODE REVIEW

**Comment by Turini** [comment]
Did you run unit tests after your changes? Travis build failed.

**Comment by silvioprog** [comment]
Hm... can you test it using Java 8? You need to change your POM file.

**Comment by garcia-jj** [comment]
Please, provide some information about your change, not a generic title without description. 

We need to understand your changes before merge, to review your code, and to check if this change will affect another classes inside this project.

**Comment by silvioprog** [comment]
Oops, sorry.

The first change allow to use the VRaptor-i18n with Java 8. The second change just removes some redundant entries, applying the refactore suggested by Intellij IDEA.

**Comment by garcia-jj** [comment]
This project should compatible with Java 7.

**Comment by silvioprog** [comment]
Any chance to use this plugin with Java 8? VRaptor seems work fine with Java 8: http://www.vraptor.org/en/cookbook/building-a-web-application-with-java8-vraptor4-wildfly/.

**Comment by Turini** [comment]
none of these changes break compatibility with Java 7

**Comment by Turini** [comment]
@silvioprog it already works with java 8, there is no restriction about that

**Comment by silvioprog** [comment]
@Turini , yes, it works like a charm with Jetty and Tomcat. The problem occurs in Wildfly 8.2.0. Sorry for I forget this information.

**Comment by silvioprog** [comment]
Really it break the Java 7 compatibility. =/ Please remove that. I'll use Jetty instead of Wildfly in my server, but would be very nice to see VRaptor-i18n working with Wildfly too.

**Comment by Turini** [comment]
why it break the Java 7 compatibility?

**Comment by silvioprog** [comment]
So, I don't know. =/ Can you test this changes in Java 7?

I'll make a small demo to reproduce the error using the latest stable release of VRaptor-i18n...

**Comment by Turini** [comment]
None of these changes break compatibility with Java 7. It's impossible.
About wildfly, forget it for now. it's another issue (unrelated this this PR)
But for some how your code is not compiling in travis... I can check it later.

**Comment by silvioprog** [comment]
OK buddy. But I deleted my fork. =( I'll recreate it, fix the test case and send a new pull request.

**Comment by Turini** [comment]
ok then, so can I close this PR?

**Comment by silvioprog** [comment]
Yes, you can! :+1:

**Comment by garcia-jj** [comment]
You can ask us in mailing list, if you prefer, to help you with your code.

**Pull request closed without merging**
